server:
  port: 8081
spring:
  application:
    name: hmdp
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/hmdp?useSSL=false&serverTimezone=UTC
    username: root
    password: zero
  redis:
    host: 192.168.200.154
    port: 6379
    password: 780415
    lettuce:
      pool:
        max-active: 10
        max-idle: 10
        min-idle: 1
        time-between-eviction-runs: 10s
  jackson:
    default-property-inclusion: non_null # JSON处理时忽略非空字段

  # RabbitMq
  rabbitmq:
    host: 192.168.200.154
    #用户名
    username: admin
    #密码
    password: admin
    #虚拟主机
    virtual-host: my_vhost
    #端口
    port: 5672
    listener:
      simple:
        #消费者最小数量
        concurrency: 10
        #消费者最大数量
        max-concurrency: 10
        #限制消费者每次只处理一条消息，处理完在继续下一条消息
        prefetch: 1
        #启动时是否默认启动容器，默认true
        auto-startup: true
        #被拒绝时重新入队
        default-requeue-rejected: true
    template:
      #发布重试，默认false
      retry:
        enabled: true
        #重试时间默认1000ms
        initial-interval: 1000ms
        #重试最大次数，默认3次
        max-attempts: 3
        #重试最大间隔时间：10000ms
        max-interval: 10000ms
        #重试的间隔系数,每次间隔时间是前一次时间的倍数
        multiplier: 1
mybatis-plus:
  type-aliases-package: com.hmdp.entity # 别名扫描包
logging:
  level:
    com.hmdp: debug

